ALTER TABLE sesiones
ADD COLUMN pausas_detectadas JSONB DEFAULT '[]';

CREATE TABLE IF NOT EXISTS log_pausas (
    id SERIAL PRIMARY KEY,
    sesion_id INTEGER NOT NULL REFERENCES sesiones(id) ON DELETE CASCADE,
    inicio TIMESTAMP NOT NULL,
    fin TIMESTAMP NOT NULL,
    duracion DOUBLE PRECISION NOT NULL,
    fuente VARCHAR(20) NOT NULL
);

